"use client";
import { useState, useEffect } from "react";

export default function InstructorDashboard() {
  const [question, setQuestion] = useState("");
    const [type, setType] = useState("multiple-choice");
      const [options, setOptions] = useState("Yes, No, Maybe");
        const [activePoll, setActivePoll] = useState<any>(null);
          const [baseUrl, setBaseUrl] = useState("");

            useEffect(() => {
                setBaseUrl(window.location.origin);
                  }, []);

                    const createPoll = async () => {
                        const formattedOptions = type === "multiple-choice" ? options.split(",").map(o => o.trim()) : [];
                            const res = await fetch("/api/poll", {
                                  method: "POST",
                                        headers: { "Content-Type": "application/json" },
                                              body: JSON.stringify({ question, type, options: formattedOptions }),
                                                  });
                                                      const data = await res.json();
                                                          setActivePoll(data);
                                                            };

                                                              useEffect(() => {
                                                                  const interval = setInterval(async () => {
                                                                        const res = await fetch(`/api/poll`);
                                                                              const data = await res.json();
                                                                                    setActivePoll(data);
                                                                                        }, 2000);
                                                                                            return () => clearInterval(interval);
                                                                                              }, []);

                                                                                                const studentPollUrl = `${baseUrl}/poll/${activePoll?.id || "live"}`;

                                                                                                  return (
                                                                                                      <div style={{ padding: "30px", fontFamily: "sans-serif", maxWidth: "900px", margin: "auto" }}>
                                                                                                            <h1>Instructor Dashboard</h1>
                                                                                                                  
                                                                                                                        <div style={{ background: "#f9f9f9", padding: "20px", borderRadius: "8px", marginBottom: "20px" }}>
                                                                                                                                <h3>Create New Poll</h3>
                                                                                                                                        <label>Type: </label>
                                                                                                                                                <select value={type} onChange={(e) => setType(e.target.value)} style={{ width: "100%", padding: "8px", marginBottom: "10px" }}>
                                                                                                                                                          <option value="multiple-choice">Multiple Choice</option>
                                                                                                                                                                    <option value="rating">Rating Scale (1-5)</option>
                                                                                                                                                                              <option value="open-ended">Open-Ended Text</option>
                                                                                                                                                                                      </select>

                                                                                                                                                                                              <label>Question: </label>
                                                                                                                                                                                                      <input type="text" placeholder="Ask a question..." value={question} onChange={(e) => setQuestion(e.target.value)} style={{ width: "100%", padding: "8px", marginBottom: "10px" }} />

                                                                                                                                                                                                              {type === "multiple-choice" && (
                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                    <label>Options (comma separated): </label>
                                                                                                                                                                                                                                                <input type="text" value={options} onChange={(e) => setOptions(e.target.value)} style={{ width: "100%", padding: "8px", marginBottom: "10px" }} />
                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                          <button onClick={createPoll} style={{ background: "green", color: "white", padding: "10px 20px", border: "none", cursor: "pointer", width: "100%" }}>
                                                                                                                                                                                                                                                                                    Launch Poll
                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                  </div>

                                                                                                                                                                                                                                                                                                        {activePoll && (
                                                                                                                                                                                                                                                                                                                <div style={{ display: "flex", gap: "20px" }}>
                                                                                                                                                                                                                                                                                                                          <div style={{ flex: 1, background: "#fff", padding: "20px", border: "1px solid #ddd", borderRadius: "8px" }}>
                                                                                                                                                                                                                                                                                                                                      <h3>Live Results: {activePoll.question}</h3>
                                                                                                                                                                                                                                                                                                                                                  <p>Total Responses: <b>{Object.keys(activePoll.votes || {}).length}</b></p>
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                          {activePoll.type === "multiple-choice" && activePoll.options.map((opt: string, idx: number) => {
                                                                                                                                                                                                                                                                                                                                                                                        const total = Object.keys(activePoll.votes || {}).length;
                                                                                                                                                                                                                                                                                                                                                                                                      const count = Object.values(activePoll.votes || {}).filter((v: any) => v === idx).length;
                                                                                                                                                                                                                                                                                                                                                                                                                    const pct = total > 0 ? Math.round((count / total) * 100) : 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div key={idx} style={{ marginBottom: "10px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>{opt} — {count} votes ({pct}%)</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div style={{ background: "#eee", height: "20px", borderRadius: "4px", overflow: "hidden" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div style={{ width: `${pct}%`, background: "blue", height: "100%" }}></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {activePoll.type === "open-ended" && Object.entries(activePoll.votes || {}).map(([user, val]: [string, any], i) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div key={i} style={{ background: "#f1f1f1", padding: "8px", margin: "5px 0", borderRadius: "4px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <b>{user}:</b> {val}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div style={{ textAlign: "center", background: "#fff", padding: "20px", border: "1px solid #ddd", borderRadius: "8px" }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p><b>Scan to Vote:</b></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <img src={`https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=${encodeURIComponent(studentPollUrl)}`} alt="QR" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p style={{ fontSize: "10px", wordBreak: "break-all", marginTop: "10px" }}>{studentPollUrl}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }